version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: orders_db
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=0"
    ports:
      - "5432:5432"
    volumes:
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql
